### ISSUE TITLE
Does this work with FileVault enabled?

### ISSUE THREAD

**Issue by thewmf** [cgarduno1garduno/Macbook-Security#1]
The point of FileVault is to prevent this.

**Comment by cgarduno1garduno** [comment]
I haven't tried it with FileVault, but I will test it out and update the post. In the past hour or so I've been learning more about this issue. Although many people don't consider this an issue, I think this is problematic for those that are not computer savvy. I've recently learned that this will work with any OS so even if FileVault prevents it, others may be vulnerable if they don't encrypt! This mainly concerns me considering some friends and family that are absolutely NOT computer savvy. It seems that this shouldn't be possible on any device, and as a growing number of people are computer savvy, this seems like it could become more problematic for some populations. 

What I would like to see, at a minimum, is the terminal request the HD's password before giving me access. I think this is reasonable to expect and it will help protect sensitive data.

**Comment by cgarduno1garduno** [comment]
It does not work with FileVault!
