### ISSUE TITLE
Here is how that works

### ISSUE THREAD

**Issue by Vaelatern** [cgarduno1garduno/Macbook-Security#2]
Simple: Your files are not encrypted.
All you are doing is mounting a hard drive in a distro. Even that back-and-forth you describe with restarting the terminal is not necessary.
Here is what happens.
1. You start Ubuntu and start doing things.
2. Ubuntu looks for drives, like any good consumer Linux.
3. Ubuntu notices this conveniently placed drive, and tries to mount it.
4. Not seeing anything cryptographic, Ubuntu is successful.
5. You `cd` to where Ubuntu mounted the drive, and discover `/Users`
6. Then you see the little lock icon, which just means permissions are not loose enough to allow a normal user to use the directory.
7. No fear! You shall become the super user! Since there is nothing cryptographic stopping you, just UNIX permissions, you are successful.

This is not a problem. This is why people should encrypt their data (such as with File Vault). Whatever you think is the password protection is obviously not actually there beyond to prevent access from a running system.
Disclaimer: I do not own a Mac running a recent OSX so I do not know what you mean by "password protected" but from your description, you just learned why encryption is important.

**Comment by cgarduno1garduno** [comment]
Thank you for taking the time to explain this! You made it very clear, and I did indeed learn why encryption is important. 

It still bums me out that employees at the Apple store (and Best Buy) discourage some users from using encryption because "it's too complicated". I still think it's a problem, but only because from my experience encryption is not commonly emphasized when you are shopping for a new computer. Seeing as how a basic login password doesn't do much to protect users I think they should strongly encourage all users to encrypt.

**Comment by Vaelatern** [comment]
My pleasure!

However there is a dark side to encryption. It's actually is pretty hard. There are a few approaches, with upsides and downsides.
1. *Encrypted home*. On Linux and BSDs, this means encrypting the directories in `/home`. On OSX, this means encrypting the folders under `/Users` (and is, I believe, what FileVault does). This is wonderful, it protects your data if it's in your home folder. It also opens a person up to a sort of attack: the programs on your computer outside of `/home` or `/Users` could become corrupted (intentionally) and your computer could betray you next time you unlock your files. Nevertheless, this is a decent first step.
2. *Encrypted root* Encrypt the entire hard drive! Great, except now you need a way to start the computer. This is not without landmines, mostly with getting from relatively basic levels of computer operation to a full operating system, but this time needing to decrypt a lot before you can really get started. There are variants of this technique, and all need to solve the problem of getting the computer started. This mechanism IS hard.

But both mechanisms have a fundemental dangers that the average computer user may not be willing to face. If you lose the password, you can't get your photos off of your computer. If certain parts of the disk get wiped, something really essential for decryption might also get wiped, and then you can't access your photos even if you do have the password.

But you are correct. Your login password does nothing to protect you from an in-person attacker.
